services:
  postgres:
    image: postgres:16
    container_name: pg_local
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5435:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    command: >
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c maintenance_work_mem=2GB
      -c shared_buffers=1GB
      -c work_mem=128MB
      -c max_wal_size=2GB
